site_name: Rancher Opni
site_url: https://github.com/rancher/opni-docs
repo_url: https://github.com/rancher/opni
edit_uri: ""
strict: false
theme:
  features:
    - navigation.instant
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: "Work Sans"
  logo: "assets/logo-horizontal-opni-no-bg.png"
  favicon: "assets/favicon.png"
plugins:
  - search
markdown_extensions:
  - codehilite
  - attr_list
  - def_list
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - toc:
      permalink: true
nav:
  - index.md
  - Deployment:
      - deployment/quickstart.md
      - deployment/basic.md
      - deployment/advanced.md
  - Setup Guides:
      - setup/gpu.md
      - setup/log-shipping.md
      - setup/setup-grafana-dashboard.md
      - setup/metrics.md
  - Architecture:
      - architecture/highlevel.md
  - Configuration:
      - configuration/elasticsearch.md
      - configuration/gpuadapter.md
      - configuration/logadapter.md
      - configuration/nats.md
      - configuration/opnicluster.md
      - configuration/pretrainedmodel.md
      - configuration/s3.md
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/extra.js
extra:
  version:
    provider: mike
  analytics:
    provider: google
    property: UA-56382716-14
